spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All tasks
    database:
      type: postgres
    auto-deployment-enabled: false

server:
  port: 8084